apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: meta-ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  path: apps/ingress-nginx/overlays/lab
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: helm-ingress-nginx-controller
      namespace: ns-ingress-nginx
  patches:
    - path: ingress-nginx-values-patch.yaml   # âœ… appelle le fichier patch externe
