apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xwiki
spec:
  rules:
    - host: xwiki.integration.nudger.logo-solutions.fr   # ðŸ‘ˆ diffÃ©rent
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xwiki-svc
                port:
                  number: 8080
