apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: nudger-gitops-integration-runner
  namespace: ns-open4goods-integration
spec:
  replicas: 1
  template:
    spec:
      repository: loicgo29/nudger-gitops
      labels:
        - self-hosted
        - nudger-gitops
        - integration
      envFrom:
        - secretRef:
            name: actions-runner-controller   # âœ… cherche le secret
            namespace: actions-runner-system  # ðŸ‘ˆ ajoute ce champ

